version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service

  status_service:
    depends_on:
      - user_service
      - statusDB
    build: ./status_service
    restart: unless-stopped
  
  story_service:
    depends_on:
      - user_service
      - minio
      - storyDB
    build: ./story_service
    restart: unless-stopped

  user_service:
    depends_on:
      - userDB
    image: ./user_service
    restart: unless-stopped
 
  userDB:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    volumes:
      - /bitnami/mongodb
        
  statusDB:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    volumes:
      - /bitnami/mongodb
        
  storyDB:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    volumes:
      - /bitnami/mongodb

  minio:
    image: bitnami/minio:2022
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - /minio_data